name: Node CI

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Use Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: "18"
      - name: npm install, build, and test
        run: |
          npm i
          npm run build --if-present
        env:
          CI: true
      - name: Archive production artifacts
        uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4
        with:
          name: dist
          path: |
            dist
